package pages.project;

import lombok.Getter;

public enum Column {
    NPS_SINGLE("NPS_SINGLE"),
    NPS_ROW("NPS_ROW"),
    SINGLE_SELECT_RADIO_ROW("SINGLE_SELECT_RADIO_ROW"),
    SINGLE_SELECT_RADIO_COLUMN("SINGLE_SELECT_RADIO_COLUMN"),
    SINGLE_SELECT_BUTTON_ROW("SINGLE_SELECT_BUTTON_ROW"),
    SINGLE_SELECT_BUTTON_COLUMN("SINGLE_SELECT_BUTTON_COLUMN"),
    SINGLE_SELECT_DROPDOWN_SINGLE("SINGLE_SELECT_DROPDOWN_SINGLE"),
    SINGLE_SELECT_DROPDOWN_ROW("SINGLE_SELECT_DROPDOWN_ROW"),
    SINGLE_SELECT_DROPDOWN_COLUMN("SINGLE_SELECT_DROPDOWN_COLUMN"),

    MULTI_SELECT_CHECKBOX_ROW("MULTI_SELECT_CHECKBOX_ROW"),
    MULTI_SELECT_CHECKBOX_COLUMN("MULTI_SELECT_CHECKBOX_COLUMN"),
    MULTI_SELECT_BUTTON_ROW("MULTI_SELECT_BUTTON_ROW"),
    MULTI_SELECT_BUTTON_COLUMN("MULTI_SELECT_BUTTON_COLUMN"),
    MULTI_SELECT_DROPDOWN_SINGLE("MULTI_SELECT_DROPDOWN_SINGLE"),
    MULTI_SELECT_DROPDOWN_ROW("MULTI_SELECT_DROPDOWN_ROW"),
    MULTI_SELECT_DROPDOWN_COLUMN("MULTI_SELECT_DROPDOWN_COLUMN"),

    NUMERIC_NUMBER_TEXTBOX_SINGLE("NUMERIC_NUMBER_TEXTBOX_SINGLE"),
    NUMERIC_NUMBER_TEXTBOX_ROW("NUMERIC_NUMBER_TEXTBOX_ROW"),
    NUMERIC_NUMBER_TEXTBOX_COLUMN("NUMERIC_NUMBER_TEXTBOX_COLUMN"),

    NUMERIC_CURRENCY_TEXTBOX_SINGLE("NUMERIC_CURRENCY_TEXTBOX_SINGLE"),
    NUMERIC_CURRENCY_TEXTBOX_ROW("NUMERIC_CURRENCY_TEXTBOX_ROW"),
    NUMERIC_CURRENCY_TEXTBOX_COLUMN("NUMERIC_CURRENCY_TEXTBOX_COLUMN"),

    NUMERIC_DECIMAL_TEXTBOX_SINGLE("NUMERIC_DECIMAL_TEXTBOX_SINGLE"),
    NUMERIC_DECIMAL_TEXTBOX_ROW("NUMERIC_DECIMAL_TEXTBOX_ROW"),
    NUMERIC_DECIMAL_TEXTBOX_COLUMN("NUMERIC_DECIMAL_TEXTBOX_COLUMN"),

    AUTOSUM_NUMBER_TEXTBOX_ROW("AUTOSUM_NUMBER_TEXTBOX_ROW"),
    AUTOSUM_NUMBER_TEXTBOX_COLUMN("AUTOSUM_NUMBER_TEXTBOX_COLUMN"),
    AUTOSUM_CURRENCY_TEXTBOX_ROW("AUTOSUM_CURRENCY_TEXTBOX_ROW"),
    AUTOSUM_CURRENCY_TEXTBOX_COLUMN("AUTOSUM_CURRENCY_TEXTBOX_COLUMN"),
    AUTOSUM_DECIMAL_TEXTBOX_ROW("AUTOSUM_DECIMAL_TEXTBOX_ROW"),
    AUTOSUM_DECIMAL_TEXTBOX_COLUMN("AUTOSUM_DECIMAL_TEXTBOX_COLUMN"),

    ESSAY_TEXTAREA_SINGLE("ESSAY_TEXTAREA_SINGLE"),
    ESSAY_TEXTAREA_ROW("ESSAY_TEXTAREA_ROW"),
    ESSAY_TEXTAREA_COLUMN("ESSAY_TEXTAREA_COLUMN"),
    ESSAY_TEXTBOX_SINGLE("ESSAY_TEXTBOX_SINGLE"),
    ESSAY_TEXTBOX_ROW("ESSAY_TEXTBOX_ROW"),
    ESSAY_TEXBOX_COLUMN("ESSAY_TEXBOX_COLUMN"),

    STAR_SCALE_NUMERIC_NUMBER_SINGLE("STAR_SCALE_NUMERIC_NUMBER_SINGLE"),
    STAR_SCALE_NUMERIC_NUMBER_ROW("STAR_SCALE_NUMERIC_NUMBER_ROW"),
    RANK_ORDINAL_DRAG_LINEAR_ROW("RANK_ORDINAL_DRAG_LINEAR_ROW"),
    RANK_ORDINAL_ASSIGN_LINEAR_ROW("RANK_ORDINAL_ASSIGN_LINEAR_ROW"),
    RANK_ORDINAL_DRAG_ZONE_ROW("RANK_ORDINAL_DRAG_ZONE_ROW"),
    SLIDER_SCALE_NUMERIC_NUMBER_SINGLE("SLIDER_SCALE_NUMERIC_NUMBER_SINGLE"),
    SLIDER_SCALE_NUMERIC_NUMBER_ROW("SLIDER_SCALE_NUMERIC_NUMBER_ROW"),
    SLIDER_SCALE_NUMERIC_CURRENCY_SINGLE("SLIDER_SCALE_NUMERIC_CURRENCY_SINGLE"),
    SLIDER_SCALE_NUMERIC_CURRENCY_ROW("SLIDER_SCALE_NUMERIC_CURRENCY_ROW"),
    SLIDER_SCALE_NUMERIC_DECIMAL_SINGLE("SLIDER_SCALE_NUMERIC_DECIMAL_SINGLE"),
    SLIDER_SCALE_NUMERIC_DECIMAL_ROW("SLIDER_SCALE_NUMERIC_DECIMAL_ROW"),

    NUMERIC_NUMBER_TEXTBOX_GRID("NUMERIC_NUMBER_TEXTBOX_GRID"),
    NUMERIC_CURRENCY_TEXTBOX_GRID("NUMERIC_CURRENCY_TEXTBOX_GRID"),
    NUMERIC_DECIMAL_TEXTBOX_GRID("NUMERIC_DECIMAL_TEXTBOX_GRID"),
    AUTOSUM_NUMBER_TEXTBOX_GRID("AUTOSUM_NUMBER_TEXTBOX_GRID"),
    AUTOSUM_DECIMAL_TEXTBOX_GRID("AUTOSUM_DECIMAL_TEXTBOX_GRID"),
    AUTOSUM_CURRENCY_TEXTBOX_GRID("AUTOSUM_CURRENCY_TEXTBOX_GRID"),
    ESSAY_TEXT_AREA_GRID("ESSAY_TEXT_AREA_GRID"),
    ESSAY_TEXTBOX_GRID("ESSAY_TEXTBOX_GRID"),

    SINGLE_SELECT_RADIO_BUTTON_GRID("SINGLE_SELECT_RADIO_BUTTON_GRID"),
    SINGLE_SELECT_BUTTON_GRID("SINGLE_SELECT_BUTTON_GRID"),
    SINGLE_SELECT_DROPDOWN_GRID("SINGLE_SELECT_DROPDOWN_GRID"),
    MULTI_SELECT_CHECKBOX_GRID("MULTI_SELECT_CHECKBOX_GRID"),
    MULTI_SELECT_BUTTON_GRID("MULTI_SELECT_BUTTON_GRID"),


    MULTI_SELECT_DROPDOWN_GRID("MULTI_SELECT_DROPDOWN_GRID"),
    RANK_MAXIMUM_DIFFERENCE_SCALE("RANK_MAXIMUM_DIFFERENCE_SCALE"),
    DRAGDROP_SINGLE_ASSIGNMENT_BUCKET("DRAGDROP_SINGLE_ASSIGNMENT_BUCKET"),
    DRAGDROP_SINGLE_ASSIGNMENT_BUTTON("DRAGDROP_SINGLE_ASSIGNMENT_BUTTON"),

    Q1_R3_OTHER("Q1_R3_OTHER"),
    Q1_R4_OTHER("Q1_R4_OTHER"),


    RESPONDENT_Id("Respondent Id"),
    STATUS("status");

    Column(String value) {
        this.value = value;
    }

    @Getter
    private final String value;
}
